apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project3
spec:
  destination:
    namespace: project3
    server: https://kubernetes.default.svc
  project: default
  source:
    path: project3
    repoURL: https://github.com/Mokk12/argocd-test-2.git
    targetRevision: main
  syncPolicy:
    automated: {}
