apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project2
spec:
  destination:
    namespace: project2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: project2
    repoURL: https://github.com/Mokk12/argocd-test-2.git
    targetRevision: main
  syncPolicy:
    automated: {}
